name: spike-train-tda
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pip
  - pip:
      - persim
      - ripser
      - elephant
      - neo
      - quantities
      - gudhi
